job_titles = [
"Account Manager",
"Accounts Payable",
"Administrative Assistant",
"Advertising Layout Artist",
"Advertising Manager",
"Analytics Lead",
"Art Director",
"Artificial Intelligence Engineer",
"Assistant District Attorney",
"Associate Attorney",
"Associate Director Engineering"
"Audio Engineer",
"Big Data Developer",
"Brand Project Manager",
"Business Analyst",
"Business Manager",
"Buyer",
"CCO",
"CDO",
"Certified Chef Principal",
"CFO",
"Chief Compliance Officer",
"Chief Council",
"Chief Customer Officer",
"Chief Data Officer",
"Chief Data Scientist",
"Chief Diversity Officer",
"Chief Executive Officer",
"Chief Financial Officer",
"Chief Human Resources Officer",
"Chief Information Officer",
"Chief Information Security Officer",
"Chief Marketing Officer",
"Chief Operating Officer",
"Chief Product Officer",
"Chief Technology Officer",
"CHRO",
"CIO",
"Cloud Solutions Architect",
"CMO",
"Commericial And Business Development Manager",
"Communication Assistant.",
"Communication Officer",
"Community Manager",
"COO",
"Corporate Journalist",
"CPO",
"Creative Director",
"Criminal Defense Attorney",
"CTO",
"Customer Success Specialist",
"Cybersecurity Engineer",
"Cybersecurity Specialist",
"Data Consultant",
"Data Engineer",
"Data Protection Officer",
"Data Scientist",
"Database Administrator",
"Database Manager",
"Deputy Ciso",
"Designer/Editor",
"Developer",
"Developer Advocate",
"Devops Engineer",
"Digital Learning Manager",
"Digital Marketing Consultant",
"Direct Marketing Manager",
"Director Of Communication",
"Director Of Inside Sales",
"Director, Product Development",
"Director, Site Reliability",
"Director, Software Development",
"Director of Talent Acquisition",
"District Attorney",
"Ediscovery Expert",
"Executive Director",
"Export Assistant",
"Finance Manager",
"Fintech Director",
"Front End Developer",
"General Counsel",
"Head, Brand Development",
"Head Council",
"Head Mechanic",
"Head Of Department",
"Head of Maintenance",
"Human Resources Assistant",
"Human Resources Manager",
"Industrial Computer Technician",
"Information System Architect",
"Innovation Project Manager",
"Io IT Network Engineer",
"IOT Expert",
"IT Intern",
"IT Project Manager",
"IT Recruiter",
"Junior Developer",
"Junior Marketing Associate",
"Lawyer",
"Lead Developer",
"Lead Support Engineer",
"Machine Learning Engineer",
"Manager, Data Analytics Operations",
"Market Analyst",
"Marketing Director",
"Marketing Research Manager",
"Media Planner",
"Merchandising Manager",
"Microcomputer Salesperson",
"Motion Designer",
"Network Engineer",
"Operations Manager",
"Press Attachã©",
"Principal Software Developer",
"Private Equity Analyst",
"Processing Department",
"Processing Manager",
"Procurement",
"Product Manager",
"Profit Center Manager",
"Promotion Officer",
"Real Estate Agent",
"Real Estate Lawyer",
"Recruitment Manager",
"Referencing Technician",
"Regional Director",
"Sales Agent",
"Sales Representative",
"Security Engineer",
"Senior Attorney",
"Senior Director, Engineering",
"Senior Manager, Infrastructure",
"Senior Marketing Director",
"Senior Product Development Support Manager",
"Senior Project Manager",
"Senior Software Engineering Manager",
"Senior UI Designer", 
"Senior Vice President, Software Dev. And Engineering",
"Seo Consultant (Mo/Seo Consultant)",
"Site Reliability Engineer",
"Social Media Consultant",
"Social Media Manager",
"Solicitor",
"Sr. Director, Platform Development (Hosting/Review)",
"Store Manager",
"Support Engineer",
"SVP Managed Services & Discovery Analytics",
"Team Leader",
"Tech Support Analyst",
"Technical Sales Engineer",
"Telecom Installer",
"Telecommunications Technician",
"Traffic Manager",
"Underwriter",
"UI Lead",
"UX Designer",
"UX Director",
"Vice President Software Development",
"Vice President, Portfolio Commercialization",
"Vice President, Talent Acquisition",
"VP, Global Product Engineering",
"VP, Global Support Services",
"VP, Innovation & Technology",
"Web Designer",
"Webdesigner",
"Webmaster"
]
